// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analyze": {
            "post": {
                "description": "Upload a ZIP or TAR family file and get a JSON analysis report",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Analyze an artifact",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Artifact file to analyze",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/report.Report"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "report.Artifact": {
            "type": "object",
            "properties": {
                "input_path": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                }
            }
        },
        "report.Node": {
            "type": "object",
            "properties": {
                "compressed_size_bytes": {
                    "type": "integer"
                },
                "hash_error": {
                    "type": "string"
                },
                "mode": {
                    "type": "integer"
                },
                "modified_time": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "path_normalization_error": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "report.Report": {
            "type": "object",
            "properties": {
                "artifact": {
                    "$ref": "#/definitions/report.Artifact"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/report.Node"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/report.Stats"
                }
            }
        },
        "report.Stats": {
            "type": "object",
            "properties": {
                "bytes_hashed": {
                    "type": "integer"
                },
                "dirs": {
                    "type": "integer"
                },
                "files": {
                    "type": "integer"
                },
                "files_skipped": {
                    "type": "integer"
                },
                "other": {
                    "type": "integer"
                },
                "symlinks": {
                    "type": "integer"
                },
                "total_nodes": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Decouple API",
	Description:      "Analyzes build artifacts (ZIP, JAR, TAR, etc.) and returns a JSON report.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
